# -*- coding: utf-8 -*-
"""CNN Clásicas para Clasificación de Lesiones Dermatológicas-Bueno.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HMo99341SeZlLoRuNXEMvdOAKw0dNXAl

# CNN Clásicas para Clasificación de Lesiones Dermatológicas

En este notebook se evalúa cómo diferentes arquitecturas clásicas de redes neuronales convolucionales (CNN) pueden utilizarse para clasificar imágenes dermatoscópicas. El objetivo es evaluar modelos ampliamente reconocidos en visión artificial, como ResNet50, DenseNet121 e InceptionV3 y compararlos bajo un mismo pipeline experimental.
Estas arquitecturas representan la base del deep learning moderno y constituyen un excelente punto de partida para establecer una línea base sólida frente a modelos más recientes, como Transformers o redes orientadas al análisis temporal.

## Dataset empleado

Para este experimento se emplea el dataset HAM10000, un conjunto de más de 10.000 imágenes dermatoscópicas que incluye siete tipos de lesiones cutáneas. Es uno de los datasets más utilizados en investigación dermatológica debido a su diversidad y a la calidad de sus imágenes.
Cada imagen se redimensionará a 224 × 224 píxeles, lo que permite trabajar con arquitecturas preentrenadas en ImageNet sin modificar su estructura interna.
Este dataset presenta un desbalanceo significativo entre clases, lo que lo convierte en un escenario realista y desafiante para evaluar la capacidad de generalización de los modelos.

## Objetivo del experimento

El objetivo principal de este experimento es comparar el rendimiento de tres arquitecturas CNN clásicas en la clasificación de lesiones dermatológicas:
* ResNet50
* DenseNet121
* InceptionV3
Cada modelo se entrenará bajo las mismas condiciones para garantizar una comparación justa y reproducible.

## Preparación del entorno

En esta sección configuraremos el entorno de trabajo, instalaremos las dependencias necesarias y cargaremos las librerías que utilizaremos a lo largo del experimento.
"""

# Instalación de dependencias
!pip install tensorflow matplotlib seaborn scikit-learn opencv-python-headless

import tensorflow as tf
import random
import tensorflow.keras as keras
from sklearn.metrics import roc_curve, auc
from sklearn.preprocessing import label_binarize
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import ResNet50, DenseNet121, InceptionV3
from tensorflow.keras.applications.resnet50 import preprocess_input as resnet_preprocess
from tensorflow.keras.applications.densenet import preprocess_input as densenet_preprocess
from tensorflow.keras.applications.inception_v3 import preprocess_input as inception_preprocess
import cv2
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import classification_report, confusion_matrix
from tensorflow.keras.preprocessing.image import load_img
import os
import shutil
import pandas as pd
import kagglehub
from tensorflow.keras.applications.resnet50 import preprocess_input as preprocess_resnet
from tensorflow.keras.applications.densenet import preprocess_input as preprocess_densenet
from tensorflow.keras.applications.inception_v3 import preprocess_input as preprocess_inception
from sklearn.model_selection import train_test_split
from tensorflow.keras.preprocessing.image import ImageDataGenerator

print("GPUs:", tf.config.list_physical_devices('GPU'))

gpus = tf.config.list_physical_devices('GPU')
for gpu in gpus:
    tf.config.experimental.set_memory_growth(gpu, True)

"""## Carga y preprocesamiento del dataset

Antes de entrenar los modelos, es necesario preparar los datos. En este bloque:
* cargaremos las imágenes desde el directorio del dataset
* aplicaremos técnicas de data augmentation
* normalizaremos las imágenes según el esquema de cada arquitectura
* dividiremos el dataset en entrenamiento y validación. Esto permite mejorar la robustez del modelo y evitar sobreajuste.
"""

DATASET_PATH = kagglehub.dataset_download("kmader/skin-cancer-mnist-ham10000")
IMG_SIZE = (224, 224)
BATCH_SIZE = 32

OUTPUT_DIR = "/content/ham10000_dir"

shutil.rmtree(OUTPUT_DIR, ignore_errors=True)

df = pd.read_csv(os.path.join(DATASET_PATH, "HAM10000_metadata.csv"))

img1 = os.path.join(DATASET_PATH, "HAM10000_images_part_1")
img2 = os.path.join(DATASET_PATH, "HAM10000_images_part_2")


train_df, temp_df = train_test_split(
    df,
    test_size=0.30,
    stratify=df["dx"],
    random_state=42
)

val_df, test_df = train_test_split(
    temp_df,
    test_size=0.50,
    stratify=temp_df["dx"],
    random_state=42
)

def copy_images(dataframe, split_name):
    for _, r in dataframe.iterrows():
        cls = r["dx"]
        img_id = r["image_id"]

        src = os.path.join(img1, f"{img_id}.jpg")
        if not os.path.exists(src):
            src = os.path.join(img2, f"{img_id}.jpg")

        if not os.path.exists(src):
            continue

        dst_dir = os.path.join(OUTPUT_DIR, split_name, cls)
        os.makedirs(dst_dir, exist_ok=True)

        dst = os.path.join(dst_dir, f"{img_id}.jpg")

        if not os.path.exists(dst):
            shutil.copy(src, dst)

copy_images(train_df, "train")
copy_images(val_df, "val")
copy_images(test_df, "test")

class_counts = df["dx"].value_counts().sort_index()
total = len(df)

table = pd.DataFrame({
    "Clase": class_counts.index,
    "Num_muestras": class_counts.values,
    "Porcentaje": (class_counts.values / total * 100).round(2)
})

print(table)
print("Total:", total)

# Data Augmentation
train_datagen = ImageDataGenerator(
    horizontal_flip=True,
    rotation_range=20,
    zoom_range=0.2
)

val_datagen = ImageDataGenerator(rescale=1./255)
test_datagen = ImageDataGenerator(rescale=1./255)

train_gen = train_datagen.flow_from_directory(
    os.path.join(OUTPUT_DIR, "train"),
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode="categorical",
    shuffle=True
)

val_gen = val_datagen.flow_from_directory(
    os.path.join(OUTPUT_DIR, "val"),
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode="categorical",
    shuffle=False
)

test_gen = test_datagen.flow_from_directory(
    os.path.join(OUTPUT_DIR, "test"),
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode="categorical",
    shuffle=False
)

print(train_gen.class_indices)

"""## Construcción de los modelos CNN

En este apartado definiremos una función que construye un modelo CNN a partir de una arquitectura base preentrenada en ImageNet. Esta función:
* congela las capas convolucionales
* añade una capa de global average pooling
* incorpora dropout para evitar sobreajuste
* finaliza con una capa densa para clasificación multiclase.

Esto nos permite reutilizar el conocimiento aprendido por los modelos en millones de imágenes.
"""

from tensorflow.keras import layers

IMG_SIZE = (224, 224)
NUM_CLASSES = 7


def build_model(base_model):

    base_model.trainable = False

    inputs = keras.Input(shape=(224,224,3))
    x = base_model(inputs, training=False)

    x = layers.GlobalAveragePooling2D()(x)
    x = layers.Dropout(0.3)(x)
    outputs = layers.Dense(NUM_CLASSES, activation="softmax")(x)

    model = keras.Model(inputs, outputs)

    model.compile(
        optimizer=keras.optimizers.Adam(1e-4),
        loss="categorical_crossentropy",
        metrics=["accuracy"]
    )

    return model


# modelos base
resnet_base = ResNet50(weights="imagenet", include_top=False, input_shape=(224,224,3))
dense_base = DenseNet121(weights="imagenet", include_top=False, input_shape=(224,224,3))
inception_base = InceptionV3(weights="imagenet", include_top=False, input_shape=(224,224,3))

# modelos finales
resnet_model = build_model(resnet_base)
dense_model = build_model(dense_base)
inception_model = build_model(inception_base)

"""## Fine-tunning

En esta sección realizaremos fine‑tuning, es decir:
* descongelar las últimas capas del modelo
* entrenar con una tasa de aprendizaje baja
* mejorar la capacidad del modelo para adaptarse al dominio dermatológico.
"""

from sklearn.utils.class_weight import compute_class_weight

y_train = train_gen.classes

weights = compute_class_weight(
    class_weight="balanced",
    classes=np.unique(y_train),
    y=y_train
)

class_weights = dict(enumerate(weights))

print(class_weights)
def fine_tune(model, base_model, train_gen, val_gen, name):

    print(f"\n Fine-tuning {name}")

    base_model.trainable = True

    fine_tune_at = len(base_model.layers) - 30

    for layer in base_model.layers[:fine_tune_at]:
        layer.trainable = False

    model.compile(
        optimizer=keras.optimizers.Adam(1e-5),
        loss="categorical_crossentropy",
        metrics=["accuracy"]
    )

    history = model.fit(
        train_gen,
        validation_data=val_gen,
        epochs=10,
        class_weight=class_weights
    )

    return history

"""## Transfer Learning

En esta sección se definen tres arquitecturas de deep learning preentrenadas:

- ResNet50
- DenseNet121
- InceptionV3

Estas redes se cargan con pesos preentrenados en ImageNet y se adaptan al problema de clasificación de lesiones cutáneas del dataset HAM10000.

"""

history_resnet = fine_tune(resnet_model, resnet_base, train_gen, val_gen, "ResNet50")

history_dense = fine_tune(dense_model, dense_base, train_gen, val_gen, "DenseNet121")

history_inception = fine_tune(inception_model, inception_base, train_gen, val_gen, "InceptionV3")

"""# Evaluación"""

tf.keras.backend.clear_session()
resnet_eval = resnet_model.evaluate(val_gen, verbose=1)
dense_eval = dense_model.evaluate(val_gen, verbose=1)
inception_eval = inception_model.evaluate(val_gen, verbose=1)

print("ResNet50:", resnet_eval)
print("DenseNet121:", dense_eval)
print("InceptionV3:", inception_eval)

"""## Evaluación y métricas
Descripción del bloque
Una vez entrenados los modelos, evaluaremos su rendimiento utilizando:
* accuracy
* F1-score
* matriz de confusión
* un análisis cualitativo de errores

Esto nos permitirá identificar qué modelos funcionan mejor y en qué clases presentan dificultades.

## Análisis de errores

Aunque las métricas globales son útiles, en un entorno clínico es igual o más importante entender qué tipo de errores comete el modelo.
En esta sección visualizaremos ejemplos de imágenes mal clasificadas para identificar patrones
"""

def show_misclassified(model, generator, title, n=12):

    y_true = generator.classes
    y_pred = np.argmax(model.predict(generator), axis=1)

    class_names = list(generator.class_indices.keys())

    # índices mal clasificados
    wrong_idx = np.where(y_true != y_pred)[0]

    if len(wrong_idx) == 0:
        print(f"No errors for {title}")
        return

    selected = np.random.choice(wrong_idx, min(n, len(wrong_idx)), replace=False)

    plt.figure(figsize=(15, 10))
    plt.suptitle(f"Misclassified examples - {title}", fontsize=16)

    for i, idx in enumerate(selected):

        img_path = generator.filepaths[idx]
        img = plt.imread(img_path)

        true_label = class_names[y_true[idx]]
        pred_label = class_names[y_pred[idx]]

        plt.subplot(3, 4, i+1)
        plt.imshow(img)
        plt.axis("off")
        plt.title(f"T:{true_label}\nP:{pred_label}", fontsize=9)

    plt.tight_layout()
    plt.show()


show_misclassified(resnet_model, val_gen, "ResNet50")
show_misclassified(dense_model, val_gen, "DenseNet121")
show_misclassified(inception_model, val_gen, "InceptionV3")

"""## Curvas ROC y AUC por clase

Accuracy no siempre refleja el rendimiento real en datasets desbalanceados como HAM10000.
Las curvas ROC permiten evaluar:
* sensibilidad vs especificidad
* rendimiento por clase
* capacidad discriminativa del modelo
"""

def plot_roc(model, generator, title):

    y_true = generator.classes
    y_score = model.predict(generator)

    n_classes = y_score.shape[1]

    y_true_bin = label_binarize(y_true, classes=list(range(n_classes)))

    plt.figure(figsize=(8,6))

    aucs = []

    for i in range(n_classes):

        fpr, tpr, _ = roc_curve(y_true_bin[:, i], y_score[:, i])
        roc_auc = auc(fpr, tpr)
        aucs.append(roc_auc)

        plt.plot(fpr, tpr, lw=2, label=f"Class {i} (AUC = {roc_auc:.2f})")

    plt.plot([0,1],[0,1],'k--')

    plt.title(f"ROC Curve - {title}")
    plt.xlabel("False Positive Rate")
    plt.ylabel("True Positive Rate")
    plt.legend()
    plt.grid()
    plt.show()

    print(f"\nMean AUC ({title}):", np.mean(aucs))


plot_roc(resnet_model, val_gen, "ResNet50")
plot_roc(dense_model, val_gen, "DenseNet121")
plot_roc(inception_model, val_gen, "InceptionV3")

"""# Matriz de confusión

"""

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay


def plot_cm(y_true, y_pred, classes, title):

    cm = confusion_matrix(y_true, y_pred)

    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=classes)

    fig, ax = plt.subplots(figsize=(8,6))
    disp.plot(ax=ax, cmap="Blues", xticks_rotation=45)

    plt.title(title)
    plt.show()


plot_cm(y_true, resnet_pred, class_names, "Confusion Matrix ResNet50")
plot_cm(y_true, dense_pred, class_names, "Confusion Matrix DenseNet121")
plot_cm(y_true, inception_pred, class_names, "Confusion Matrix InceptionV3")

"""## Comparación entre modelos

A continuación se presentan gráficas comparativas da cada uno de los modelos.
"""

plt.figure(figsize=(10,6))

plt.plot(history_resnet.history["val_accuracy"], label="ResNet50")
plt.plot(history_dense.history["val_accuracy"], label="DenseNet121")
plt.plot(history_inception.history["val_accuracy"], label="InceptionV3")

plt.title("Comparación de Accuracy en validación")
plt.xlabel("Épocas")
plt.ylabel("Accuracy")
plt.legend()
plt.grid(True)
plt.show()


plt.figure(figsize=(10,6))

plt.plot(history_resnet.history["val_loss"], label="ResNet50")
plt.plot(history_dense.history["val_loss"], label="DenseNet121")
plt.plot(history_inception.history["val_loss"], label="InceptionV3")

plt.title("Comparación de Loss en validación")
plt.xlabel("Épocas")
plt.ylabel("Loss")
plt.legend()
plt.grid(True)
plt.show()

summary = pd.DataFrame({
    "Model": ["ResNet50", "DenseNet121", "InceptionV3"],
    "Val Accuracy": [
        max(history_resnet.history["val_accuracy"]),
        max(history_dense.history["val_accuracy"]),
        max(history_inception.history["val_accuracy"])
    ],
    "Val Loss": [
        min(history_resnet.history["val_loss"]),
        min(history_dense.history["val_loss"]),
        min(history_inception.history["val_loss"])
    ]
})

print(summary)

"""## Explicabilidad del modelo


La explicabilidad es un componente fundamental en modelos aplicados a la salud. Aunque las CNN pueden alcanzar una alta precisión, su naturaleza de “caja negra” dificulta entender qué regiones de la imagen influyen en la decisión del modelo. Para mitigar este problema, utilizaremos técnicas de Explainable AI (XAI), concretamente Grad-CAM, que permite visualizar los mapas de activación relevantes para cada predicción.

Esto es especialmente importante en dermatología, donde los profesionales necesitan saber por qué un modelo considera que una lesión es benigna o maligna, y si la red está prestando atención a características clínicas relevantes (asimetría, bordes, color, textura…)

Grad‑CAM (Gradient‑weighted Class Activation Mapping) genera un mapa de calor que muestra qué regiones de la imagen han contribuido más a la predicción del modelo.

- Colores rojos: zonas con mayor importancia.
- Colores azules: zonas con menor relevancia.

Esto nos permite verificar si el modelo está mirando la lesión o si se distrae con artefactos, sombras o bordes.
"""

import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
import cv2

def gradcam(img_array, base_model, layer_name):

    grad_model = tf.keras.models.Model(
        inputs=base_model.input,
        outputs=[base_model.get_layer(layer_name).output]
    )

    with tf.GradientTape() as tape:
        conv_outputs = grad_model(img_array, training=False)
        tape.watch(conv_outputs)
        loss = tf.reduce_mean(conv_outputs)

    grads = tape.gradient(loss, conv_outputs)
    pooled = tf.reduce_mean(grads, axis=(0, 1, 2))

    conv_outputs = conv_outputs[0]
    heatmap = tf.reduce_sum(conv_outputs * pooled, axis=-1)

    heatmap = tf.maximum(heatmap, 0)
    heatmap = heatmap / (tf.reduce_max(heatmap) + 1e-8)

    return heatmap.numpy()


def show(img_path, base_model, layer_name, title):

    img = tf.keras.utils.load_img(img_path, target_size=(224, 224))
    x = tf.keras.utils.img_to_array(img)
    x = np.expand_dims(x, axis=0)

    heatmap = gradcam(x, base_model, layer_name)
    heatmap = cv2.resize(heatmap, (224, 224))
    heatmap = np.uint8(255 * heatmap)
    heatmap = cv2.applyColorMap(heatmap, cv2.COLORMAP_JET)

    img = np.array(img)

    overlay = cv2.addWeighted(
        cv2.cvtColor(img, cv2.COLOR_RGB2BGR),
        0.6,
        heatmap,
        0.4,
        0
    )

    plt.figure(figsize=(6,6))
    plt.imshow(cv2.cvtColor(overlay, cv2.COLOR_BGR2RGB))
    plt.title(title)
    plt.axis("off")
    plt.show()


class_names = list(val_gen.class_indices.keys())
img_path = val_gen.filepaths[0]

show(img_path, resnet_base, "conv5_block3_out", "Grad-CAM - ResNet50")
show(img_path, dense_base, "conv5_block16_concat", "Grad-CAM - DenseNet121")
show(img_path, inception_base, "mixed10", "Grad-CAM - InceptionV3")